require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: true
  Exclude:
    - "bin/**/*"

Gemspec/RequireMFA:
  Enabled: false

Style/Documentation:
  Enabled: false

# RSpec
RSpec/NestedGroups:
  Enabled: false
